### ISSUE TITLE
直接下载编译报错: This file requires compiler and library support for the ISO C++ 2011 standard

### ISSUE THREAD

**Issue by 473867143** [amov-lab/px4_command#2]
环境是:Ubuntu16.04+gazebo7+kinetic
问题描述:git clone 之后,执行catkin_make出现编译错误如下:

/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \

文件请求支持c++ 11标准

**Comment by swrdZWJ** [comment]
我今天也遇到了相同的问题，该怎么解决啊？

**Comment by 473867143** [comment]
在px4_command目录下面,打开CMakeLists.txt文件.把第五行注释取消掉,重新catkin_make.
取消注释后代码为add_compile_options(-std=c++11)
